version: "3.9"
services:
  discovery:
    build:  ./Discovery-server
    ports:
      - "8761:8761"
    image: "discovery:v1"



  candidate:
    build: ./Candidate
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8082:8082"
    image: "candidat:v1"
    depends_on:
      - mysqldb

  resource:
    build: ./resource
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8083:8083"
    image: "resource:v1"
    depends_on:
      - mysqldb



  mysqldb:
    container_name: mysqldb
    image: mysql:8
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: resource
      MYSQL_ROOT_PASSWORD: root


  gateway:
    build: ./GatewayApi

    ports:
      - "8085:8085"
    image: "gateway:v1"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/


  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    restart: always
volumes:
  keycloak-data:
    external: false



