version: "3.9"
services:
  discovery:
    build:  ./Discovery-server
    ports:
      - "8761:8761"
    image: "discovery:v1"

  front-ms:
    build: ./AngularMicroService-main
    image: ms-frontend:v1
    ports:
      - 4200:4200


  candidate:
    build: ./Candidat
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8082:8082"
    image: "candidat:v1"
    depends_on:
      - mysqldb

  resource:
    build: ./resource
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8083:8083"
    image: "resource:v1"
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:8
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: resource
      MYSQL_ROOT_PASSWORD: root

  cour:
    build: ./cour
    ports:
      - "8086:8086"
    image: "cours:v1"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    depends_on:
      - mysqldb

  reclamation:
    build: ./Reclamations
    ports:
      - "8088:8088"
    image: "reclamations:v1"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    depends_on:
      - mysqldb


  gateway:
    build: ./GatewayApi

    ports:
      - "8085:8085"
    image: "gateway:v1"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/


  seances:
    build: ./Node-Ms
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=discovery
    ports:
      - "8081:8081"
    image: "seances:v1"


  plannings:
    build: ./plannings
    ports:
      - "8087:8087"
    image: "plannings:v1"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    depends_on:
      - h2


  h2:
    container_name: 'h2'
    hostname: 'h2'
    image: 1000kit/h2
    ports:
      - "8181:8181"
      - "1521:1521"
    volumes:
      - h2-data:/opt/h2-data
volumes:
  h2-data:


